


 threshold : 0.8

 input_file :   C:\Users\floodai\UNOSAT_FloodAI_v2\1data\4final\predict_INPUT\835_1_IMAGE_HH_SRA_spot_042.tif                  

 output_folder :    C:\Users\floodai\UNOSAT_FloodAI_v2\1data\4final\predict_INPUT   

 output_filename  :  SENSOR_DATETIME_728_1.tif

 analysis_extent :    C:/Users/floodai/UNOSAT_FloodAI_v2/1data/4final/predict_INPUT/extent_INPUT   



