


 threshold : 0.8

 input_file : Y:\1NEW_DATA\1data\1raw\dset_DLR_TSX\current\dims_op_oc_dfd2_695958835_1\TSX-1.SAR.L1B\TSX1_SAR__EEC_RE___SL_S_SRA_20240316T032045_20240316T032046\IMAGEDATA\IMAGE_HH_SRA_spot_042.tif                

 output_folder :    C:\Users\floodai\UNOSAT_FloodAI_v2\1data\4final\predict_INPUT   

 output_filename  :  SENSOR_wedpm_729_1.tif

 analysis_extent :    C:/Users/floodai/UNOSAT_FloodAI_v2/1data/4final/predict_INPUT/extent_INPUT   



