


 threshold : 0.8

 input_file :   Y:\1NEW_DATA\1data\1raw\TC20241212MOZ\20241218_SC\urn_ogc_def_EOP_DLR_C582_N84_A_SM_strip_009_R_2024-12-18T16_01_39_116303Z-product\dims_op_oc_dfd2_696555804_1\TSX-1.SAR.L1B\TDX1_SAR__EEC_RE___SM_S_SRA_20241218T160139_20241218T160144\IMAGEDATA\IMAGE_HH_SRA_strip_009.tif                  

 output_folder :    C:\Users\floodai\UNOSAT_FloodAI_v2\1data\4final\predict_INPUT   

 output_filename  :  SENSOR_DATETIME_804_1.tif

 analysis_extent :    C:/Users/floodai/UNOSAT_FloodAI_v2/1data/4final/predict_INPUT/extent_INPUT   



