
name :  'focal_loss_sweep1' 
project :  'TSX' 
program : 'UNOSAT_FloodAI_v2.train_new' 
method :  grid  
metric :   
  goal :  minimize    
  name :  val_loss_epoch
parameters :  
  batch_size :   
    value : 16
  max_epoch :   
    value : 1
  focal_alpha :   
    value : 0.65
  focal_gamma :  
    value : 1 
command :
- python
- -m 
- scripts.training.train_new