
name :  focal_loss_sweep  
project :  focal_loss_sweep 
program : UNOSAT_FloodAI_v2.train_new 
method :  grid  
metric :   
  goal :  minimize    
  name :  validation_loss   
parameters :  
  batch_size :   
    value : 16
  max_epochs :   
    value : 2
  focal_alpha :   
    # values : [6, 6.5, 7]  
    values : [6]  
  focal_gamma :  
    # values : [0.2 , 0.3, 0.4, 0.5  ]  
    values : [0.2 , 0.3 ]  
command :
- python
- -m 
- scripts.training.train_new