
name :  'focal_loss_sweep1' 
project :  'TSX' 
program : 'UNOSAT_FloodAI_v2.train_new' 
method :  grid  
metric :   
  goal :  minimize    
  name :  val_loss_epoch
parameters :  
  batch_size :   
    value : 16
  max_epoch :   
    value : 20
  focal_alpha :   
    value : None
  focal_gamma :  
    value : None
  bce_weight :
    values : [0.6, 0.65, 0.7, 0.75, 0.8, ]
command :
- python
- -m 
- scripts.training.train_new